# Generated by Django 4.1.4 on 2023-02-18 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NIST_171_Controls',
            fields=[
                ('family', models.CharField(blank=True, max_length=250, null=True)),
                ('control_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('control_txt', models.TextField(blank=True, null=True)),
                ('discussion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NIST_172_Controls',
            fields=[
                ('family', models.CharField(blank=True, max_length=250, null=True)),
                ('control_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('control_txt', models.TextField(blank=True, null=True)),
                ('discussion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NIST_53_Controls',
            fields=[
                ('control_name', models.CharField(max_length=200)),
                ('control_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('control_txt', models.TextField()),
                ('discussion', models.TextField()),
                ('cmmc_level', models.PositiveIntegerField(null=True)),
                ('control_id_171', models.TextField(null=True)),
                ('control_id_172', models.TextField(null=True)),
                ('related_controls', models.CharField(blank=True, max_length=200, null=True)),
                ('applicable_systems', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('population', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country')),
            ],
        ),
    ]
