# Generated by Django 4.1.4 on 2023-02-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nist_53_controls',
            name='control_txt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nist_53_controls',
            name='discussion',
            field=models.TextField(null=True),
        ),
    ]
