# Generated by Django 4.1.4 on 2023-02-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_nist_53_controls_control_txt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nist_53_controls',
            name='related_controls',
            field=models.TextField(null=True),
        ),
    ]
