# Generated by Django 4.1.4 on 2023-02-18 01:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_city_country_remove_purchase_item_delete_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIST_171_Controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=30)),
                ('control_txt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NIST_172_Controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=30)),
                ('control_txt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NIST_53_Controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(max_length=30)),
                ('control_id', models.CharField(max_length=30)),
                ('control_txt', models.TextField()),
                ('discussion', models.TextField()),
                ('cmmc_level', models.CharField(max_length=30)),
                ('applicable_systems', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=8)),
                ('control_id_171', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.nist_171_controls')),
                ('control_id_172', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.nist_172_controls')),
            ],
        ),
    ]
