# Generated by Django 4.1.4 on 2023-02-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_nist_171_controls_nist_172_controls_nist_53_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nist_53_controls',
            name='cmmc_level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nist_53_controls',
            name='control_name',
            field=models.CharField(max_length=200),
        ),
    ]
