# Generated by Django 4.1.4 on 2023-02-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_company_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_profile',
            old_name='cert_req',
            new_name='certification_requirements',
        ),
    ]
