# Generated by Django 4.1.4 on 2023-02-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_nist_53_controls_cmmc_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nist_171_controls',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nist_172_controls',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nist_53_controls',
            name='id',
        ),
        migrations.AlterField(
            model_name='nist_171_controls',
            name='control_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nist_172_controls',
            name='control_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nist_53_controls',
            name='control_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
