# Generated by Django 4.1.4 on 2023-02-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_nist_171_controls_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nist_53_controls',
            name='related_controls',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
