# Generated by Django 4.1.4 on 2023-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_nist_53_controls_related_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nist_53_controls',
            name='applicable_systems',
            field=models.TextField(),
        ),
    ]
