# Generated by Django 4.1.4 on 2023-02-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_nist_53_controls_applicable_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='nist_171_controls',
            name='discussion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nist_171_controls',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nist_172_controls',
            name='discussion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nist_172_controls',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nist_171_controls',
            name='control_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nist_172_controls',
            name='control_txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
